MvcCoreTest/Controllers/AciklamaController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcCoreTest.Context;
using MvcCoreTest.Entiti;
using MvcCoreTest.Models;
using MvcCoreTest.Services.Base;

namespace MvcCoreTest.Controllers
{
    public class AciklamaController : Controller
    {
        private readonly ArabaContext _context;
        private readonly IAciklamaServis _aciklamaServis;
        private readonly IArabaServis _arabaServis;

        public AciklamaController(IAciklamaServis aciklamaServis, IArabaServis arabaServis)
        {
            _aciklamaServis = aciklamaServis;
            _arabaServis = arabaServis;
        }
        public IActionResult Index()
        {
            return View(_aciklamaServis.Query().ToList());
        }
        public IActionResult Details(int? id)
        {
            if (id == null)
                return View("MyError", "Id gereklidir!");
            var model = _aciklamaServis.Query().SingleOrDefault(r => r.Id == id.Value);
            if (model == null)
                return View("MyError", "Yorum bulunamadı!");
            return View(model);
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(string Detay, DateTime Tarih)
        {
            AciklamaModel model = new AciklamaModel()
            {
                Detay = Detay,
                Tarih = Tarih               
            };
            _aciklamaServis.Add(model);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int? id)
        {
            if (!id.HasValue)
                return View("MyError", "Id gereklidir!");
            var model = _aciklamaServis.Query().SingleOrDefault(d => d.Id == id.Value);
            if (model == null)
                return View("MyError", "Yorum bulunamadı!");
            ViewBag.Araba = new SelectList(_arabaServis.Query().ToList(), "Id", "Adi", model.Araba);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(AciklamaModel aciklama)
        {
            if (ModelState.IsValid)
            {
                var result = _aciklamaServis.Update(aciklama);
                if (result == ResultStatus.Success)
                {
                    TempData["Message"] = "Açıklama Güncellendi.";
                    return RedirectToAction(nameof(Index));
                }
                return View("MyError"); // 
            }
            ViewBag.Araba = new SelectList(_arabaServis.Query().ToList(), "Id", "Adi", aciklama.Araba);
            return View(aciklama);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return View("MyError", "Id gereklidir!");
            var result = _aciklamaServis.Delete(id.Value);
            if (result == ResultStatus.Success)
            {
                TempData["Message"] = "Yorum Silindi.";
                return RedirectToAction(nameof(Index));
            }
            return View("MyError"); 
        }
    }
}

MvcCoreTest/Controllers/ArabaController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreTest.Models;
using MvcCoreTest.Services.Base;

namespace MvcCoreTest.Controllers
{
    public class ArabaController : Controller
    {
        private readonly IArabaServis _arabaServis;
        private readonly IAciklamaServis _aciklamaServis;

        public ArabaController(IArabaServis arabaServis, IAciklamaServis aciklamaServis)
        {
            _arabaServis = arabaServis;
            _aciklamaServis = aciklamaServis;
        }
        public IActionResult Index()
        {
            List<ArabaModel> model = _arabaServis.Query().ToList();
            return View(model);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest("İd gereklidir");
            }
            ArabaModel model = _arabaServis.Query().SingleOrDefault(m => m.Id == id.Value);
            if (model == null)
            {
                return NotFound("Araba Bulunamadı");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Create(string Adi, short? UretimYili, double? Fiyat)
        {
            ArabaModel model = new ArabaModel()
            {
                Adi = Adi,
                UretimYili = UretimYili,
                Fiyat = Fiyat
            };
            _arabaServis.Add(model);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View("MyError", "Id gereklidir!");
            }
            ArabaModel model = _arabaServis.Query().SingleOrDefault(m => m.Id == id.Value);
            if (model == null)
            {
                return View("MyError", "Araba bulunamadı!");
            }
                
            return View(model);

        }
        [HttpPost]
        public IActionResult Edit(ArabaModel model) 
        {
            if (ModelState.IsValid)
            {
                ResultStatus result = _arabaServis.Update(model);
                if (result == ResultStatus.Success)
                {
                    TempData["Message"] = "Araç bilgileri güncellendi..";
                    return RedirectToAction(nameof(Index));
                }
                if (result == ResultStatus.Exception)
                {
                    return View("MyError");
                }
            }
            
            return View(model);
        }
        public IActionResult Delete(int? id) 
        {
            if (id == null)
                return View("MyError", "Id Gereklidir");
            ResultStatus result = _arabaServis.Delete(id.Value);
            if (result == ResultStatus.Success)
            {
                TempData["Message"] = "Araba Silindi.";
                return RedirectToAction(nameof(Index));
            }
            if (result == ResultStatus.RelationalEntitiesExist)
            {
                TempData["Message"] = "Detay Olduğu İçin Araba Kaydı Silinemez!";
                return RedirectToAction(nameof(Index));
            }
            return View("MyError"); 
        }
    }
}

MvcCoreTest/Controllers/UreticisController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcCoreTest.Context;
using MvcCoreTest.Entiti;
using MvcCoreTest.Models;
using MvcCoreTest.Services.Base;

namespace MvcCoreTest.Controllers
{
    public class UreticisController : Controller
    {

        private readonly IUreticiServis _ureticiServis;
        private readonly IArabaServis _arabaServis;

        public UreticisController(IUreticiServis ureticiServis, IArabaServis arabaServis)
        {
            _ureticiServis = ureticiServis;
            _arabaServis = arabaServis;
        }

        
        public IActionResult Index()
        {
            return View(_ureticiServis.Query().ToList());
        }

        
        public IActionResult Details(int? id)
        {
            if (!id.HasValue)
                return View("MyError", "Id Gereklidir!");
            var model = _ureticiServis.Query().SingleOrDefault(d => d.Id == id.Value);
            if (model == null)
                return View("MyError", "Üretici bulunamadı!");
            return View(model);
        }
       
        public IActionResult Create()
        {           
            return View();
        }
        
        [HttpPost]
        //[ValidateAntiForgeryToken]
        
        public IActionResult Create(string FirmaAdi, string FirmaLokasyon, bool UretimDurumu)
        {
            UreticiModel model = new UreticiModel()
            {
                FirmaAdi = FirmaAdi,
                FirmaLokasyon = FirmaLokasyon,
                UretimDurumu = UretimDurumu
            };
            _ureticiServis.Add(model);
            return RedirectToAction(nameof(Index));           
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View("MyError", "Id Gereklidir!");
            }
            UreticiModel model = _ureticiServis.Query().SingleOrDefault(d => d.Id == id.Value);
            if (model == null)
            {
                return View("MyError", "Üretici bulunamadı!");
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public IActionResult Edit(UreticiModel uretici)
        {
            if (ModelState.IsValid)
            {
                ResultStatus result = _ureticiServis.Update(uretici);
                if (result == ResultStatus.Success)
                {
                    TempData["Message"] = "Üretici Güncellendi.";
                    return RedirectToAction(nameof(Index));
                }
                if (result == ResultStatus.Exception)
                {
                    return View("MyError");
                }
            }           
            return View(uretici);
        }

       
        public IActionResult Delete(int? id)
        {
            if (!id.HasValue)
                return View("MyError", "Id Gereklidir!");
            var model = _ureticiServis.Query().SingleOrDefault(d => d.Id == id.Value);
            if (model == null)
                return View("MyError", "Uretici Bulunamadı!");
            return View(model);
        }

        [HttpPost, ActionName("Delete")] 
        [ValidateAntiForgeryToken]
        
        public IActionResult DeleteConfirmed(int id)
        {
            var result = _ureticiServis.Delete(id);
            if (result == ResultStatus.Success)
            {
                TempData["Message"] = "Üretici Silindi.";
                return RedirectToAction(nameof(Index));
            }
            return View("MyError"); 
        }

        
    }
}

MvcCoreTest/Views/Shared/MyError.cshtml
@model string
<h2 class="text-danger">Error!</h2>
<p class="text-danger">@Model</p>

MvcCoreTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a href="/Database/Seed" class="nav-link text-dark">Kayıt Getir</a>
                        </li>
                        <li>
                            @Html.ActionLink("Araba Listesi", "Index", "Araba", null, new{@class="nav-link text-dark"})
                        </li>      
                        <li>
                            @Html.ActionLink("Üretici Listesi", "Index", "Ureticis", null, new{@class="nav-link text-dark"})
                        </li> 
                        <li>
                            @Html.ActionLink("Açıklama Listesi", "Index", "Aciklama", null, new{@class="nav-link text-dark"})
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Hakkında</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Abdullah Okuyucu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Hakkında</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>